version: '3.1'
services:
  app:
    container_name: app-springboot-postgresql
    image: spring-practices-demo
    build: ./
    ports:
      - "8099:8099"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=kla4st#en
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres